### ISSUE TITLE
Formating CSV export column headers

### ISSUE THREAD

**Issue by kani-rifluxyss** [filipdanic/spicy-datatable#20] opened 2018-12-03 11:23 UTC
I would like to have the csv header to be formatted like label "Name" instead of just "name" in key.
Is it possible?

{
    key: 'name',
    label: 'Name',
    sort: true
  }

**Comment by filipdanic** [comment] 2018-12-17 10:23
Hey @kani-rifluxyss, 👋

Thanks for the issue and sorry for not responding!

Hmm, this was actually always the intended behavior. I’m not sure why the `label` key is not being used. I’ll try to fix it, but the relevant code for this is in the method `handleDownloadCSV` in case anyone else wants to have a go.

**Comment by kani-rifluxyss** [comment] 2018-12-18 14:12
![image](https://user-images.githubusercontent.com/5585046/50159563-989b9e80-029c-11e9-836d-9fcca152df50.png)


Changed this, and it seems to be working. Thanks.

**Comment by filipdanic** [comment] 2018-12-19 12:00
By that I would guess the bug is in the `filterApplicableKeysForCSVDownload` method.

**Comment by filipdanic** [comment] 2018-12-21 10:06
Should be fixed properly in `spicy-datatable@0.8.1`

**Closed as completed by filipdanic** 2018-12-21 10:06 UTC
Labels: bug
